#!/bin/sh
#
# usage of the script (sh multipeakcall.sh sample_name fastq_location1 fastq_location2 output_folder)
# using MACS1.4, MACS2, Sicer and RSEG
# created by Vivek Das
##Commands

s=$1
sinloc1=$2
sinloc2=$3
soutloc=$4
#sbedout=$4
GENOME=/path_to/softwares/IGVTools/genomes/mm9.chrom.sizes
peaks=/path_to/softwares/HOMER/.//bin/findPeaks 

sicerloc=/path_to/softwares/SICER_V1.1/SICER/
sicerbed=/path_to/vdas/serena_b/ChIPSeq/FASTQ_2015/bed_files

rsegpeak=/path_to/softwares/rseg-0.4.8/bin/rseg-diff
rsegmm9bed=/path_to/softwares/rseg-0.4.8/data/mm9/mouse-mm9-size.bed
rsegdeadzones=path_to/softwares/rseg-0.4.8/data/deadzones/deadzones-mm9-k51.bed



echo "Running MACS 1.4 on the bam files with control for peak calling..."
### if chip is of protein/tf turn --nomodel True is chip is of histone turn of --nomodel
macs14 -t $sinloc1/*.sorted.bam  -c $sinloc2/*.sorted.bam -n {$s}_macs14_out --format=BAM --keep-dup=1 --pvalue=1e-5 --gsize=1.87e9 --nomodel True --wig -S
echo "Finishing MACS 1.4 on the bam files..."

echo "Runnnig MACS2 on the bam files for peak calling..."
macs2 callpeak -t $sinloc1/*.sorted.bam -c $sinloc2/*.sorted.bam -f BAM -n {$s}_macs2_out --gsize=1.87e9 -B --keep-dup=1 --pvalue=1e-5 --nomodel True
#macs2 callpeak -t $sinloc1/*.sorted.bam -c $sinloc2/*.sorted.bam -f SAM -g hs -n macs2_sl_local -B -q 0.05 --slocal 5000 --llocal 50000
echo "Finising MACS2 on the bam files..."
#$peaks ${s}_tag/ -o auto -bigWig $GENOME

# !!!!Replace it with your own directory!!!
#SICER=/path_to/softwares/SICER_V1.1/SICER
mkdir $soutloc/sicerout
echo "Sicer out filers will be stored in= $soutloc/sicerout"
echo "Running SICER for peak calling..."
echo "Sicer test and control file location=$sicerbed"
sh $sicerloc/SICER.sh $sicerbed *_test.bed *_control.bed $soutloc/sicerout mm9 1 200 150 0.74 600 .01
#cd $soutloc/sicerout
#for FILENAME in *; do mv $FILENAME {$s}_$FILENAME; done
echo "Finishing Sicer..."
###using RSEG
## sort your bed files else it does not work with RSEG
#sort -k1,1 -k3,3n -k2,2n -k6,6 -o Sample_S_7_15DTAMO_S11395.sorted_final.bed Sample_S_7_15DTAMO_S11395.sorted.bed
mkdir $soutloc/rsegout
echo "outputfile name=$s"
echo "Running RSEG for peak calling..."
$rsegpeak -c $rsegmm9bed -o $soutloc/rsegout/{$s}_rseg_out.bed -i 20 -v -mode 2 -d $rsegdeadzones $sicerbed/*_test.bed $sicerbed/*_control.bed

echo "Finishing RSEG peak call.."
echo "Exiting the peak calling run of MACS14, MACS2, SICER and RSEG..."
echo "done"
